/**
 * @file hexahedron/arch/aarch64/context.S
 * @brief Context
 * 
 * 
 * @copyright
 * This file is part of the Hexahedron kernel, which is part of the Ethereal Operating System.
 * It is released under the terms of the BSD 3-clause license.
 * Please see the LICENSE file in the main repository for more details.
 * 
 * Copyright (C) 2025 Samuel Stuart
 */

.global arch_start_execution
arch_start_execution:
    ret

.global arch_enter_kthread
arch_enter_kthread:
    ret

.global arch_save_context
arch_save_context:
    ret

.global arch_load_context
arch_load_context:
    ret