on: [push, workflow_dispatch]
name: x86_64 ISO image
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Clone reduceOS repository
        uses: actions/checkout@v2
      - name: Download Docker image
        run: docker pull techdude17/ethereal-docker-x86_64
      - name: Build OS
        run: docker run -v ${GITHUB_WORKSPACE}:/opt/Ethereal -t techdude17/ethereal-docker:x86_64 /opt/build/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: build-output/hexahedron.iso
      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: build-output/sysroot/boot/hexahedron-kernel.elf
      - name: Upload initrd
        uses: actions/upload-artifact@v4
        with:
          name: initrd
          path: build-output/sysroot/boot/initrd.tar.img
